name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  build-on:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [16.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - run: npx nx-cloud start-ci-run

      - name: Build affected libraries
        run: npx nx affected --target=build --parallel --max-parallel=3

      - name: Test affected libraries
        run: npx nx affected --target=test --parallel --max-parallel=2

      - run: npx nx-cloud stop-all-agents
